[features]
seeds = false
skip-lint = false
[programs.localnet]
non_custodial_escrow = "ABhLzTy8jQMMPb7P1PbdggUFpSNn61XGrhnRRsVSRzAi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
